serverAddr = "43.139.192.176"
serverPort = 7000

auth.method = "token"
auth.token = "Season2004!!!qyr94666"

[log]
to = "/Node/logs/frpc.log"
level = "info"

[[proxies]]
name = "node_agent_$(hostname)_$(uuidgen | cut -d'-' -f1)"
type = "tcp"
localIP = "127.0.0.1"
localPort = 4321
remotePort = 8195
